src/Entity/Reprographie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Reprographie
 *
 * @ORM\Table(name="reprographie")
 * @ORM\Entity(repositoryClass="App\Repository\ReprographieRepository")
 */
class Reprographie
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_reprographie", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups("repro:read")
     */
    private $id_reprographie;

    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=255)
     * @Groups("repro:read")
     */
    private $titre;

    /**
     * @var int
     *
     * @ORM\Column(name="numeroReprographie", type="string", length=100, unique=true)
     * @Groups("repro:read")
     */
    private $numeroReprographie;

    /**
     * @var string
     *
     * @ORM\Column(name="typeDocument", type="string", length=255)
     * @Groups("repro:read")
     */
    private $typeDocument;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="dateDemande", type="datetime")
     * @Groups("repro:read")
     */
    private $dateDemande;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deadline", type="datetime")
     * @Groups("repro:read")
     */
    private $deadline;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deadline_old", type="datetime", nullable=true)
     * @Groups("repro:read")
     */
    private $deadlineOld;

    /**
     * @var string
     *
     * @ORM\Column(name="moment_journee", type="string", length=100, nullable=true)
     * @Groups("repro:read")
     */
    private $momentJournee;

    /**
     * @var bool
     *
     * @ORM\Column(name="est_urgence", type="boolean")
     * @Groups("repro:read")
     */
    private $estUrgence;

    /**
     * @var string
     *
     * @ORM\Column(name="lieu_reception", type="string", length=100)
     * @Groups("repro:read")
     */
    private $lieuReception;

    /**
     * @var string
     *
     * @ORM\Column(name="lieu_traitement", type="string", length=100, nullable=true)
     * @Groups("repro:read")
     */
    private $lieuTraitement;

    /**
     * @var string
     *
     * @ORM\Column(name="lieu_renvoie", type="string", length=100, nullable=true)
     * @Groups("repro:read")
     */
    private $lieuRenvoie;

    /**
     * @var string
     *
     * @ORM\Column(name="service_demandeur", type="string", length=10)
     * @Groups("repro:read")
     */
    private $serviceDemandeur;

    /**
     * @var string
     *
     * @ORM\Column(name="motif_annulation", type="text", nullable=true)
     * @Groups("repro:read")
     */
    private $motifAnnulation;

    /**
     * @ORM\ManyToOne(targetEntity="Taxonomie", inversedBy="repros")
     * @ORM\JoinColumn(name="id_taxonomie", referencedColumnName="id_taxonomie")
     * @Groups("repro:read")
     */
    private $id_taxonomie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="repros")
     * @ORM\JoinColumn(name="nni", referencedColumnName="nni")
     * @Groups("repro:read")
     */
    private $nni;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur")
     * @ORM\JoinColumn(name="nni_valideur_doc", referencedColumnName="nni")
     * @Groups("repro:read")
     */
    private $nni_valideur_doc;

    /**
     * @ORM\OneToMany(targetEntity="ContientDoc", mappedBy="id_reprographie" , fetch="EAGER")
     * @Groups("repro:read")
     */
    private $contientDocs;

    /**
     * @var string
     *
     * @ORM\Column(name="observations", type="text", nullable=true)
     * @Groups("repro:read")
     */
    private $observations;

    /**
     * @var string
     *
     * @ORM\Column(name="filigrane", type="string", nullable=true)
     * @Groups("repro:read")
     */
    private $filigrane;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_mise_en_place", type="datetime", nullable=true)
     * @Groups("repro:read")
     */
    private $dateMiseEnPlace;

    public function __construct()
    {
        $this->contientDocs = new ArrayCollection();
    }

    /**
     * Get id_reprographie.
     *
     * @return int
     */
    public function getIdReprographie()
    {
        return $this->id_reprographie;
    }

    /**
     * Set titre.
     *
     * @param string $titre
     *
     * @return Reprographie
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre.
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set numeroReprographie.
     *
     * @param int $numeroReprographie
     *
     * @return Reprographie
     */
    public function setNumeroReprographie($numeroReprographie)
    {
        $this->numeroReprographie = $numeroReprographie;

        return $this;
    }

    /**
     * Get numeroReprographie.
     *
     * @return int
     */
    public function getNumeroReprographie()
    {
        return $this->numeroReprographie;
    }

    /**
     * Set typeDocument.
     *
     * @param string $typeDocument
     *
     * @return Reprographie
     */
    public function setTypeDocument($typeDocument)
    {
        $this->typeDocument = $typeDocument;

        return $this;
    }

    /**
     * Get typeDocument.
     *
     * @return string
     */
    public function getTypeDocument()
    {
        return $this->typeDocument;
    }

    /**
     * Set dateDemande.
     *
     * @param \DateTime $dateDemande
     *
     * @return Reprographie
     */
    public function setDateDemande($dateDemande)
    {
        $this->dateDemande = $dateDemande;

        return $this;
    }

    /**
     * Get dateDemande.
     *
     * @return \DateTime
     */
    public function getDateDemande()
    {
        return $this->dateDemande;
    }

    /**
     * Set deadline.
     *
     * @param \DateTime $deadline
     *
     * @return Reprographie
     */
    public function setDeadline($deadline)
    {
        $this->deadline = $deadline;

        return $this;
    }

    /**
     * Get deadline.
     *
     * @return \DateTime
     */
    public function getDeadline()
    {
        return $this->deadline;
    }

    /**
     * Set deadlineOld.
     *
     * @param \DateTime $deadlineOld
     *
     * @return Reprographie
     */
    public function setDeadlineOld($deadlineOld)
    {
        $this->deadlineOld = $deadlineOld;

        return $this;
    }

    /**
     * Get deadlineOld.
     *
     * @return \DateTime
     */
    public function getDeadlineOld()
    {
        return $this->deadlineOld;
    }

    /**
     * Set momentJournee.
     *
     * @param string $momentJournee
     *
     * @return Reprographie
     */
    public function setMomentJournee($momentJournee)
    {
        $this->momentJournee = $momentJournee;

        return $this;
    }

    /**
     * Get momentJournee.
     *
     * @return string
     */
    public function getMomentJournee()
    {
        return $this->momentJournee;
    }

    /**
     * Set estUrgence.
     *
     * @param bool $estUrgence
     *
     * @return Reprographie
     */
    public function setEstUrgence($estUrgence)
    {
        $this->estUrgence = $estUrgence;

        return $this;
    }

    /**
     * Get estUrgence.
     *
     * @return bool
     */
    public function getEstUrgence()
    {
        return $this->estUrgence;
    }

    /**
     * Set lieuReception.
     *
     * @param string $lieuReception
     *
     * @return Reprographie
     */
    public function setLieuReception($lieuReception)
    {
        $this->lieuReception = $lieuReception;

        return $this;
    }

    /**
     * Get lieuReception.
     *
     * @return string
     */
    public function getLieuReception()
    {
        return $this->lieuReception;
    }

    /**
     * Set id_taxonomie.
     *
     * @param string $id_taxonomie
     *
     * @return Reprographie
     */
    public function setIdTaxonomie($id_taxonomie)
    {
        $this->id_taxonomie = $id_taxonomie;

        return $this;
    }

    /**
     * Get id_taxonomie.
     *
     * @return string
     */
    public function getIdTaxonomie()
    {
        return $this->id_taxonomie;
    }

    /**
     * Set nni.
     *
     * @param string $nni
     *
     * @return Reprographie
     */
    public function setNni($nni)
    {
        $this->nni = $nni;

        return $this;
    }

    /**
     * Get nni.
     *
     * @return string
     */
    public function getNni()
    {
        return $this->nni;
    }

    /**
     * Set nni_valideur_doc.
     *
     * @param string $nni_valideur_doc
     *
     * @return Reprographie
     */
    public function setNniValideurDoc($nni_valideur_doc)
    {
        $this->nni_valideur_doc = $nni_valideur_doc;

        return $this;
    }

    /**
     * Get nni_valideur_doc.
     *
     * @return string
     */
    public function getNniValideurDoc()
    {
        return $this->nni_valideur_doc;
    }

    /**
     * Get lieuTraitement.
     *
     * @return string
     */
    public function getLieuTraitement()
    {
        return $this->lieuTraitement;
    }

    /**
     * Set lieuTraitement.
     *
     * @param string $lieuTraitement
     *
     * @return Reprographie
     */
    public function setLieuTraitement($lieuTraitement)
    {
        $this->lieuTraitement = $lieuTraitement;

        return $this;
    }

    /**
     * Get lieuRenvoie.
     *
     * @return string
     */
    public function getLieuRenvoie()
    {
        return $this->lieuRenvoie;
    }

    /**
     * Set lieuRenvoie.
     *
     * @param string $lieuRenvoie
     *
     * @return Reprographie
     */
    public function setLieuRenvoie($lieuRenvoie)
    {
        $this->lieuRenvoie = $lieuRenvoie;

        return $this;
    }

    /**
     * Get motifAnnulation.
     *
     * @return string

templates/default/Presta/consulter-demandes-presta.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}

    <script>
        $(document).ready(function() {
            (function($) {
                $("#tableauRepro tbody").addClass("search");
                $('#filter_reference').keyup(function() {
                    var rex = new RegExp($(this).val(), 'i');
                    $('.search tr ').hide();

                    //Filtre l'objet jquery récursivement jusqu'à avoir le resultat
                    $('.search tr ').filter(function(i, v) {
                        //Récupère le 3eme élément qui est réference
                        var $t = $(this).children(":eq(" + "4" + ")");
                        return rex.test($t.text());
                    }).show();
                })

            }(jQuery));

            (function($) {
                $("#tableauRepro tbody").addClass("search");
                $('#filter_demandeur').keyup(function() {
                    var rex = new RegExp($(this).val(), 'i');
                    $('.search tr ').hide();

                    //Filtre l'objet jquery récursivement jusqu'à avoir le resultat
                    $('.search tr ').filter(function(i, v) {
                        //Récupère le 4eme élément qui est demandeur
                        var $t = $(this).children(":eq(" + "5" + ")");
                        return rex.test($t.text());
                    }).show();
                })

            }(jQuery));


            /* Pour le filtre urgent */
            $("input[name='filter_urgent']").change(function () {
                var classes = [];

                $("input[name='filter_urgent']").each(function () {
                    if ($(this).is(":checked")) { classes.push('.' + $(this).val()); }
                });

                if (classes === "") {
                    $("#tableauRepro tbody tr").show();
                } else {
                    $("#tableauRepro tbody tr").hide();

                    $("#tableauRepro tr").each(function () {
                        var show = true;
                        var row = $(this);
                        classes.forEach(function () {
                            if (row.children().eq(10).text() === "Non urgent") { show = false; }
                        });
                        if (show) { row.show(); }
                    });
                }
            });

        });
    </script>

{% endblock %}


{% block body %}

    <div class="div_titre_du_tableau">
        <span class="titre_du_tableau">Historique de demandes à facturer</span>
    </div>
    <div class="tous_les_filtres">
        Reference : <input maxlength="12" aria-label="filter_reference" size="13" type="text" name="filter_reference" id="filter_reference"  >
        Demandeur : <input aria-label="filter_demandeur" type="text" name="filter_demandeur" id="filter_demandeur">
        Urgent ? <input aria-label="filter_urgent" type="checkbox" name="filter_urgent" id="filter_urgent">


    </div>


    <table id="tableauRepro">
        <thead>
        <tr>
            <th scope="col">Statut</th>
            <th scope="col">Date</th>
            <th scope="col">A réaliser avant le</th>
            <th scope="col">Type</th>
            <th scope="col">Référence</th>
            <th scope="col">Demandeur</th>
            <th scope="col">Service</th>
            <th scope="col">Documents</th>
            <th scope="col">Lieu de réception</th>
            <th scope="col">Etat</th>
            <th scope="col">Urgence</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for repro in repros %}
            <tr>
                {% if repro.getIdTaxonomie.codeTaxonomie == 'RPD' or repro.getIdTaxonomie.codeTaxonomie == 'RAM' or repro.getIdTaxonomie.codeTaxonomie == 'RAME' or repro.getIdTaxonomie.codeTaxonomie == 'CSP' %}
                    <td align="center"><i class="fas fa-circle" style="color: green;"></i></td>
                {% elseif repro.getIdTaxonomie.codeTaxonomie == 'APD' or repro.getIdTaxonomie.codeTaxonomie == 'DRD' or repro.getIdTaxonomie.codeTaxonomie == 'DRP' or repro.getIdTaxonomie.codeTaxonomie == 'IDL' %}
                    <td align="center"><i class="fas fa-circle" style="text-align: center; color: red;"></i></td>
                {% elseif date(repro.deadline|date('F j, Y')) < date("now"|date('F j, Y')) %}
                    <td align="center"><i class="fas fa-circle" style="text-align: center; color: orange;"></i></td>
                {% else %}
                    <td align="center"><i class="fas fa-circle" style="text-align: center; color: #1f2d78;"></i></td>
                {% endif %}
                <td>{{ repro.getDateDemande | date('d/m/Y')}}</td>
                <td>{{ repro.getDeadline | date('d/m/Y') }}</td>
                <td>{{ repro.typeDocument }}</td>
                <td>{{ repro.getNumeroReprographie }}</td>
                <td>{{ repro.getNni.getNom }} {{ repro.getNni.getPrenom | capitalize }}</td>
                <td>{{ repro.getServiceDemandeur }}</td>
                <td>
                    {% for cd in repro.contientDocs %}
                        <div>{{ cd.refDocument }}</div>
                    {% endfor %}
                </td>
                <td>{{ repro.getLieuReception }}</td>
                <td>{{ repro.getIdTaxonomie.getLibelle }}</td>

                {% if repro.estUrgence %}
                    <td>Urgent</td>
                {% else %}
                    <td>Non urgent</td>
                {% endif %}


                <td>
                {% if repro.getIdTaxonomie.codeTaxonomie == 'ECDP' or repro.getIdTaxonomie.codeTaxonomie == 'TAP' or repro.getIdTaxonomie.codeTaxonomie == 'CPP' %}
                        <a href="{{ path('page_une_demande_par_le_presta', {'numeroReprographie' : repro.getNumeroReprographie}) }}">
                            <button type="button" class="btn btn-outline-dark">
                                <i class="fas fa-eye"></i>
                            </button>
                        </a>
                {% endif %}

                {% if repro.getIdTaxonomie.codeTaxonomie == 'ECP' %}

                        <a href="{{ path('page_remplir_recap_repro', {'numeroReprographie' : repro.getNumeroReprographie}) }}">
                            <button type="button" class="btn btn-outline-dark">
                                <i class="far fa-clipboard"></i>
                            </button>
                        </a>

                {% endif %}
                </td>

            </tr>
        {% endfor %}

        </tbody>
    </table>

    <span class="legende_accueil">
        <i class="fas fa-circle" style="color: #1f2d78;"></i> = Demande en cours de traitement,
        <i class="fas fa-circle" style="color: green;"></i> = Demande terminée,
        <i class="fas fa-circle" style="text-align: center; color: orange;"></i> = Demande en retard,
        <i class="fas fa-circle" style="color: red;"></i> = Demande refusée
    </span>



{% endblock %}

templates/default/Presta/consulter-une-demande-par-le-presta.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    <script>
        var close = document.getElementsByClassName("closebtn");
        var i;

        for (i = 0; i < close.length; i++) {
            close[i].onclick = function(){
                var div = this.parentElement;
                div.style.opacity = "0";
                setTimeout(function(){ div.style.display = "none"; }, 600);
            }
        }
    </script>

{% endblock %}

{% block body %}


    <div class="histo_perso_titre">Consultation de la demande N°{{ repro.getNumeroReprographie }}</div>

    <div class="histo_perso_bulle_recap">
        <span class="items_hpbr">Date de rendu : {{ repro.getDeadline | date('d/m/Y') }}</span>
        {% if repro.momentJournee == 'M' %}<span class="items_hpbr">Matin</span>{% else %}<span class="items_hpbr">Après-Midi</span>{% endif %}
        {% if repro.lieuReception == 'Courrier' %}
            <span class="items_hpbr">Lieu de réception : PILOTIMMO / Courrier interne</span>
        {% else %}
            <span class="items_hpbr">Lieu de réception : {{ repro.getLieuReception }}</span>
        {% endif %}
        <span class="items_hpbr">Demandeur : {{ repro.getNni.getNom }} {{ repro.getNni.getPrenom | capitalize }}</span>
        <span class="items_hpbr">Nature des documents : {{ repro.typeDocument }}</span>
        {% if repro.filigrane != 'Aucun' %}<span class="items_hpbr">Filigrane : {{ repro.filigrane }}</span>{% endif %}
        <span class="items_hpbr_dernier">{% if repro.estUrgence %}<td>Urgent</td>{% else %}<td>Non urgent</td>{% endif %}</span>
    </div>

    {% if doit_afficher_alerte_mail %}
        <div class="alert info" style="margin-bottom: 15px;">
            <span class="closebtn">&times;</span>
            <strong>Attention !</strong> Le refus ne peut se faire. Aucun service de mail n'a été renseigné. Veuillez contacter l'administrateur du site afin de procéder aux réglages d'envoi de mails.
        </div>
    {% endif %}

    {% if doit_afficher_alerte_contenu %}
        <div class="alert info" style="margin-bottom: 15px;">
            <span class="closebtn">&times;</span>
            <strong>Attention !</strong> Veuillez renseigner un motif de refus.
        </div>
    {% endif %}


    <table id="tableauRepro" class="tableauRepro">
        <thead>
        <tr>
            <th scope="col">Référence</th>
            <th scope="col">Indice</th>
            <th scope="col">Tampon</th>
            <th scope="col">Couleur</th>
            <th scope="col">Nombre A3</th>
            <th scope="col">Nombre A4</th>
            <th scope="col">Nombre A5</th>
            <th scope="col">Nombre A0</th>
            <th scope="col">Recto/verso</th>
            <th scope="col">Support</th>
            <th scope="col">Perforé</th>
            <th scope="col">Reliure</th>
            <th scope="col">Agrafé</th>
            <th scope="col">Plié</th>
            <th scope="col">Massicotage</th>
            <th scope="col">Plastification</th>
            <th scope="col">Documentation satellite</th>
        </tr>
        </thead>
        <tbody>

        {% for cd in contientDocs %}
            <tr>
                {% if repro.getIdTaxonomie.codeTaxonomie == 'RPD' or repro.getIdTaxonomie.codeTaxonomie == 'RAM' or repro.getIdTaxonomie.codeTaxonomie == 'RAME' or repro.getIdTaxonomie.codeTaxonomie == 'CSP' %}
                    <td>{{cd.refDocument}}</td>
                {% else %}
                    {% if cd.nomDocument %}
                        <td><a href="{{ asset('uploads/brochures/' ~ cd.nomDocument) }}" target="_blank">{{ cd.refDocument}}</a></td>
                    {% else %}
                        <td>{{cd.refDocument}}</td>
                    {% endif %}
                {% endif %}
                <td>{{ cd.indice }}</td>
                <td>{{ cd.tampon }}</td>
                {% if cd.couleur %}
                    <td>Oui</td>
                {% else %}
                    <td>Non</td>
                {% endif %}
                <td>{{ cd.nbExemplaireA3 }}</td>
                <td>{{ cd.nbExemplaireA4 }}</td>
                <td>{{ cd.nbExemplaireA5 }}</td>
                <td>{{ cd.nbExemplaireA0 }}</td>
                <td>{{ cd.rectoVerso }}</td>
                <td>{{ cd.support }}</td>
                <td>{{ cd.nbTrous }} trous</td>
                <td>{{ cd.reliement }}</td>
                {% if cd.agrafes and cd.agrafes == 1 %}
                    <td>{{ cd.agrafes }} point</td>
                {% else %}
                    <td>{{ cd.agrafes }} points</td>
                {% endif %}

                {% if cd.pliure == 1 %}
                    <td>Oui</td>
                {% else %}
                    <td>Non</td>
                {% endif %}
                {% if cd.massicotage == 1 %}
                    <td>Oui</td>
                {% else %}
                    <td>Non</td>
                {% endif %}
                {% if cd.plastification == 1 %}
                    <td>Oui</td>
                {% else %}
                    <td>Non</td>
                {% endif %}
                <td>
                    {% for documentsDansContientDocs in cd.documents.values %}
                        {% if documentsDansContientDocs.docsats.values is empty %}
                            Aucune documentation satellite.
                        {% endif %}
                        {% for docsatDansDocuments in documentsDansContientDocs.docsats.values %}
                            {% set origine = docsatDansDocuments.getOrigine %}
                            {% set docsat = docsatDansDocuments.getIdSatellite.getCodeSatellite %}
                            {% if not is_granted('ROLE_USER') %}
                                {% if origine == 'DOC' %}
                                    <span class="blue_docsat">{{ docsat }}</span>
                                {% else %}
                                    <span>{{ docsat }}</span>
                                {% endif %}
                            {% else %}
                                <span>{{ docsat }}</span>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    {% if repro.observations %}
        <div class="observations">
            <span>
                <strong>Observations :</strong>
            </span>
            <br/>
            <p>
                {{ repro.observations | nl2br }}
            </p>
        </div>
    {% endif %}

    {% if not is_granted('ROLE_USER') %}
        {% if repro.dateMiseEnPlace %}
            <div class="observations">Mise en place des documentations satellites faite le : <strong>{{ repro.dateMiseEnPlace | date('d/m/Y') }}</strong></div>
        {% endif %}
    {% endif %}

    {% if not is_granted('ROLE_USER') %}
        {% if repro.nniValideurDoc %}
            <div class="alert alert-success" role="alert">
                <i class="fas fa-thumbs-up" style="margin-right: 10px;"></i><strong>Demande validée par {{ repro.getNniValideurDoc.getNom }} {{ repro.getNniValideurDoc.getPrenom | capitalize }}</strong>
            </div>
        {% endif %}
    {% endif %}

    {% if repro.deadLine | date('d/m/Y') != repro.deadLineOld | date('d/m/Y') %}
        <div class="alert alert-info" role="alert">
            <i class="fas fa-exclamation-circle"></i> La date de rendu a été changée. Elle était datée au : <strong>{{ repro.deadLineOld | date('d/m/Y') }}</strong>
        </div>
    {% endif %}

    <br/>

    {% if repro.getIdTaxonomie.codeTaxonomie != 'ECP' %}
        {{ form_start(form) }}
            <div class="boutons_submit">
                {{ form_widget(form.submit) }}
            </div>
            <br/><br/>
            <div class="boutons_refus">
                {{ form_widget(form.motif_annulation) }}
                {{ form_widget(form.refuse) }}
            </div>

        {{ form_end(form) }}
    {% endif %}




{% endblock %}

templates/default/Presta/editer-demande-contientdocs.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="histo_perso_titre">Edition du document {{ refDocument }}</div>

    {{ form_start(form) }}

    <table id="tableauRepro" class="tableauRepro">
        <thead>
        <tr>
            <th scope="col">Nom du fichier</th>
            <th scope="col">Référence</th>
            <th scope="col">Indice</th>
            <th scope="col">Type du document</th>
            <th scope="col">Tampon</th>
            <th scope="col">Couleur</th>
            <th scope="col">Tampon</th>
            <th scope="col">Nombre A3</th>
            <th scope="col">Nombre A4</th>
            <th scope="col">Nombre A5</th>
            <th scope="col">Nombre A0</th>
            <th scope="col">Recto/verso</th>
            <th scope="col">Support</th>
            <th scope="col">Perforé</th>
            <th scope="col">Relié</th>
            <th scope="col">Agrafé</th>
            <th scope="col">Plié</th>
            <th scope="col">Massicoté</th>
            <th scope="col">Plastifié</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <input aria-label="" type="text" placeholder="{{ nom_du_doc }}" disabled>
            </td>
            <td>{{ form_widget(form.refDocument) }}</td>
            <td>{{ form_widget(form.indice) }}</td>
            <td>{{ form_widget(form.typeDocument) }}</td>
            <td>{{ form_widget(form.tampon) }}</td>
            <td>{{ form_widget(form.couleur) }}</td>
            <td>{{ form_widget(form.nbExemplaireA3) }}</td>
            <td>{{ form_widget(form.nbExemplaireA4) }}</td>
            <td>{{ form_widget(form.nbExemplaireA5) }}</td>
            <td>{{ form_widget(form.nbExemplaireA0) }}</td>
            <td>{{ form_widget(form.rectoVerso) }}</td>
            <td>{{ form_widget(form.support) }}</td>
            <td>{{ form_widget(form.nbTrous) }}</td>
            <td>{{ form_widget(form.reliement) }}</td>
            <td>{{ form_widget(form.agrafes) }}</td>
            <td>{{ form_widget(form.pliure) }}</td>
            <td>{{ form_widget(form.massicotage) }}</td>
            <td>{{ form_widget(form.plastification) }}</td>
        </tr>
        </tbody>
    </table>


    <div class="boutons_submit">
        {{ form_widget(form.retour) }}
        {{ form_widget(form.submit) }}
    </div>
    {{ form_end(form) }}



{% endblock %}