src/Entity/Taxonomie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Taxonomie
 *
 * @ORM\Table(name="taxonomie")
 * @ORM\Entity(repositoryClass="App\Repository\TaxonomieRepository")
 */
class Taxonomie
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_taxonomie", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups("repro:read")
     */
    private $id_taxonomie;

    /**
     * @var string
     *
     * @ORM\Column(name="codeTaxonomie", type="string", length=10)
     * @Groups("repro:read")
     */
    private $codeTaxonomie;

    /**
     * @var string|null
     *
     * @ORM\Column(name="libelle", type="string", length=255, nullable=true)
     * @Groups("repro:read")
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reprographie", mappedBy="id_taxonomie", cascade={"remove"})
     */
    private $repros;

    public function __construct()
    {
        $this->repros = new ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getIdTaxonomie()
    {
        return $this->id_taxonomie;
    }

    /**
     * Set codeTaxonomie.
     *
     * @param string $codeTaxonomie
     *
     * @return Taxonomie
     */
    public function setCodeTaxonomie($codeTaxonomie)
    {
        $this->codeTaxonomie = $codeTaxonomie;

        return $this;
    }

    /**
     * Get codeTaxonomie.
     *
     * @return string
     */
    public function getCodeTaxonomie()
    {
        return $this->codeTaxonomie;
    }

    /**
     * Set libelle.
     *
     * @param string|null $libelle
     *
     * @return Taxonomie
     */
    public function setLibelle($libelle = null)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Get libelle.
     *
     * @return string|null
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    public function __toString(){
        // retourne les choix entitytype du service en string
        return (string) $this->libelle;
    }
}

src/Controller/AdministrateurController.php
<?php

namespace App\Controller;

use App\Entity\ContientDoc;
use App\Entity\Docsat;
use App\Entity\Document;
use App\Entity\Reprographie;
use App\Entity\Taxonomie;
use App\Form\TaxonomieType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdministrateurController extends AbstractController
{
    public function construireChoixDatesAnnees() {
        $distance = 5;
        $yearsBefore = date('Y', mktime(0, 0, 0, date("m"), date("d"), date("Y") - $distance));
        $yearsAfter = date('Y', mktime(0, 0, 0, date("m"), date("d"), date("Y") + $distance));
        return array_combine(range($yearsBefore, $yearsAfter), range($yearsBefore, $yearsAfter));
    }

    /**
     * @Route("/administrateur", name="page_administrateur")
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function ajouterElementsMobiles(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $mail_doc = $this->getDoctrine()->getRepository(Taxonomie::class)->findOneBy(['codeTaxonomie' => 'MAILDOC']);

        if($mail_doc){
            $taxo = $mail_doc;
        }
        else{
            $taxo = new Taxonomie();
        }


        $services = $this->getDoctrine()->getRepository(Taxonomie::class)->findBy(['codeTaxonomie' => 'SRVC']);

        $form_mail_doc = $this->createForm(TaxonomieType::class,$taxo)
            ->add('maj', SubmitType::class, [
                'label' => 'Mettre à jour',
                'attr' => [
                    'class' => 'btn btn-sm mon-bouton-edf',
                    'onclick' => 'return confirm("Le mail du Pôle DOC sera mis à jour.")',
                ]
            ]);

        $dlai = array();
        $data_delai = '10';
        if($this->getDoctrine()->getRepository(Taxonomie::class)->findOneBy(['codeTaxonomie' => 'JOUR'])){
            $data_delai = $this->getDoctrine()->getRepository(Taxonomie::class)->findOneBy(['codeTaxonomie' => 'JOUR'])->getLibelle();
        }
        $form_delai = $this->createFormBuilder($dlai)
            ->add('libelle', TextType::class, [
                'label' => false,
                'data' => $data_delai,
            ])
            ->add('delai', SubmitType::class, [
                'label' => 'Mettre à jour',
                'attr' => [
                    'class' => 'btn btn-sm mon-bouton-edf',
                    'onclick' => 'return confirm("Le délai sera mis à jour.")',
                ]
            ])
            ->getForm();

        $s = array();
        $form_service = $this->createFormBuilder($s)
            ->add('libelle', TextType::class, [
                'label' => false,
            ])
            ->add('create', SubmitType::class, [
                'label' => 'Créer un service',
                'attr' => [
                    'class' => 'btn btn-sm mon-bouton-edf',
                    'onclick' => 'return confirm("Le service sera créé.")',
                ]
            ])
            ->getForm();
        $annee_supp = array();
        $form_supprimer_bdd = $this->createFormBuilder($annee_supp, array('allow_extra_fields' => true))
            ->add('annee', ChoiceType::class, [
                'choices' => $this->construireChoixDatesAnnees(),
            ])
            ->add('delete', SubmitType::class, [
                'label' => 'Supprimer',
                'attr' => [
                    'class' => 'btn btn-sm mon-bouton-edf',
                    'onclick' => 'return confirm("Toutes les reprographies de l\'année sélectionnée seront supprimées. Continuer ?")',
                ],

            ])
            ->getForm();

        $annee_pdf = array();
        $form_gen_pdf_date = $this->createFormBuilder($annee_pdf, array('allow_extra_fields' => true))
            ->add('moispdf', ChoiceType::class, [
                'choices' => [
                    'Janvier' => '01',
                    'Février' => '02',
                    'Mars' => '03',
                    'Avril' => '04',
                    'Mai' => '05',
                    'Juin' => '06',
                    'Juillet' => '07',
                    'Août' => '08',
                    'Septembre' => '09',
                    'Octobre' => '10',
                    'Novemebre' => '11',
                    'Décembre' => '12',
                ],
            ])
            ->add('anneepdf', ChoiceType::class, [
                'choices' => $this->construireChoixDatesAnnees(),
            ])
            ->add('generate', SubmitType::class, [
                'label' => 'Générer PDF',
                'attr' => [
                    'class' => 'btn btn-sm mon-bouton-edf',
                ],

            ])
            ->getForm();




        $form_mail_doc->handleRequest($request);
        $form_service->handleRequest($request);
        $form_supprimer_bdd->handleRequest($request);
        $form_gen_pdf_date->handleRequest($request);
        $form_delai->handleRequest($request);

        $doit_afficher_erreur_date_supp = false;
        $doit_afficher_erreur_pdf = false;
        $annee_pdf_form = null;
        $mois_pdf_form = null;


        if ($form_mail_doc->getClickedButton() && 'maj' === $form_mail_doc->getClickedButton()->getName())
        {
            $taxo->setCodeTaxonomie('MAILDOC');
            $em->persist($taxo);
            $em->flush();
            return $this->redirectToRoute('page_administrateur');
        }
        if ($form_delai->getClickedButton() && 'delai' === $form_delai->getClickedButton()->getName())
        {
            $dlai = $this->getDoctrine()->getRepository(Taxonomie::class)->findOneBy(['codeTaxonomie' => 'JOUR']);
//            $dlai->setCodeTaxonomie('JOUR');
            $dlai->setLibelle($form_delai->get('libelle')->getData());
            $em->persist($dlai);
            $em->flush();
            return $this->redirectToRoute('page_administrateur');
        }

        if ($form_service->getClickedButton() && 'create' === $form_service->getClickedButton()->getName())
        {
            $service = new Taxonomie();
            $service->setCodeTaxonomie('SRVC');
            $service->setLibelle($form_service->get('libelle')->getData());
            $em->persist($service);
            $em->flush();
            return $this->redirectToRoute('page_administrateur');
        }

        if ($form_gen_pdf_date->getClickedButton() && 'generate' === $form_gen_pdf_date->getClickedButton()->getName())
        {
            $annee_pdf_form = $form_gen_pdf_date->get('anneepdf')->getData();
            $mois_pdf_form = $form_gen_pdf_date->get('moispdf')->getData();

            $repros_pdf = $this->getDoctrine()->getRepository(Reprographie::class)->trouveParMoisEtAnnee($mois_pdf_form,$annee_pdf_form);
            if($repros_pdf){
                return $this->redirect($this->generateUrl('_pdf',
                    array('anneepdf' => $annee_pdf_form, 'moispdf' => $mois_pdf_form)));
            }
            else {
                $doit_afficher_erreur_pdf = true;
            }
        }

        if($form_supprimer_bdd->getClickedButton() && 'delete' === $form_supprimer_bdd->getClickedButton()->getName()){

            $annee_supp = $form_supprimer_bdd->get('annee')->getData();
            $repros_a_supp = $this->getDoctrine()->getRepository(Reprographie::class)->trouveParAnnee($annee_supp);
            if($repros_a_supp){
                foreach ($repros_a_supp as $ru){
                    $contientDocs_a_supp = $this->getDoctrine()->getRepository(ContientDoc::class)->findBy(['id_reprographie' => $ru->getIdReprographie()]);
                    foreach ($contientDocs_a_supp as $cas){
                        $docs_a_supp = $this->getDoctrine()->getRepository(Document::class)->findBy(['nomDocument' => $cas->getNomDocument()]);

                        foreach ($docs_a_supp as $das){
                            $docsat_a_supp = $this->getDoctrine()->getRepository(Docsat::class)->findBy(['id_document' => $das->getIdDocument()]);

                            foreach ($docsat_a_supp as $dsas){
                                $em->remove($dsas);
                            }
                            if($cas->getNomDocument()) {
                                if(file_exists('uploads/brochures/'.$das->getNomDocument())) {
                                    unlink('uploads/brochures/' . $das->getNomDocument());
                                }
                            }
                            $em->remove($das);
                        }
                        $em->remove($cas);
                    }

                    $em->remove($ru);

                }
                $em->flush();
                return $this->redirectToRoute('page_administrateur');
            }
            else {
                $doit_afficher_erreur_date_supp = true;
            }
        }

        $repros = $this->getDoctrine()->getRepository(Reprographie::class)->findAll();

        return $this->render('default/Administrateur/panneau-administrateur.html.twig',[
            'services' => $services,
            'form_mail_doc' => $form_mail_doc->createView(),
            'form_service' => $form_service->createView(),
            'form_supprimer_bdd' => $form_supprimer_bdd->createView(),
            'form_gen_pdf_date' => $form_gen_pdf_date->createView(),
            'form_delai' => $form_delai->createView(),
            'repros' => $repros,
            'annee_supp' => $annee_supp,
            'mois_pdf_form' => $mois_pdf_form,
            'annee_pdf_form' => $annee_pdf_form,

templates/default/Administrateur/panneau-administrateur.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    <script>
        var close = document.getElementsByClassName("closebtn");
        var i;

        for (i = 0; i < close.length; i++) {
            close[i].onclick = function(){
                var div = this.parentElement;
                div.style.opacity = "0";
                setTimeout(function(){ div.style.display = "none"; }, 600);
            }
        }
    </script>
{% endblock %}


{% block body %}

    {% if doit_afficher_erreur_date_supp %}
        <div class="alert info" style="margin-bottom: 15px;">
            <span class="closebtn">&times;</span>
            <strong>Attention !</strong> Aucune reprographie n'a été trouvée pour l'année {{ annee_supp }}.
        </div>
    {% endif %}

    {% if doit_afficher_erreur_pdf %}
        <div class="alert info" style="margin-bottom: 15px;">
            <span class="closebtn">&times;</span>
            <strong>Impossible de générer le PDF !</strong> Aucune reprographie n'a été trouvée pour le {{ mois_pdf_form }}/{{ annee_pdf_form }}.
        </div>
    {% endif %}

    <div id="accordion">
        <div class="card container">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Modifier l'e-mail du pôle DOC
                    </button>
                </h5>
            </div>

            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    {{ form_start(form_mail_doc) }}
                    E-mail pôle DOC :
                    {{ form_widget(form_mail_doc.libelle) }}
                    {{ form_widget(form_mail_doc.maj) }}
                    {{ form_end(form_mail_doc) }}
                </div>
            </div>
        </div>
        <div class="card container">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Gérer les services
                    </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body">
                    <div>
                        {{ form_start(form_service) }}
                        Créer un service :
                        {{ form_widget(form_service.libelle) }}
                        {{ form_widget(form_service.create) }}
                        {{ form_end(form_service) }}
                    </div>
                    <br />
                    {% if services %}
                        <div>
                            <table>
                                <tbody>
                                    <tr>
                                        {% for s in services %}
                                            <td><span style="font-weight: bold;">{{ s.libelle }}</span>
                                                <a onclick="return confirm('Le service {{ s.libelle }} sera supprimé. Continuer ?')" href="{{ path('page_administrateur_supprimer_service', {'id' : s.idTaxonomie}) }}">
                                                    <button type="button" class="btn btn-danger btn-sm">
                                                        <i class="fas fa-times"></i>
                                                    </button>
                                                </a>
                                            </td>
                                        {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="card container">
            <div class="card-header" id="headingThree">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                        Exporter en PDF
                    </button>
                </h5>
            </div>

            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                <div class="card-body">
                    {{ form_start(form_gen_pdf_date) }}
                    {{ form_widget(form_gen_pdf_date.moispdf) }}
                    {{ form_widget(form_gen_pdf_date.anneepdf) }}
                    {{ form_widget(form_gen_pdf_date.generate) }}
                    {{ form_end(form_gen_pdf_date) }}
                </div>
            </div>
        </div>
        <div class="card container">
            <div class="card-header" id="headingFour">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                        Purge de la base de donnée par année
                    </button>
                </h5>
            </div>

            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
                <div class="card-body">
                    {{ form_start(form_supprimer_bdd) }}
                    {{ form_widget(form_supprimer_bdd.annee) }}
                    {{ form_widget(form_supprimer_bdd.delete) }}
                    {{ form_end(form_supprimer_bdd) }}
                </div>
            </div>
        </div>
        <div class="card container">
            <div class="card-header" id="headingFive">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
                        Délai de traitement d'une reprographie
                    </button>
                </h5>
            </div>

            <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordion">
                <div class="card-body">
                    {{ form_start(form_delai) }}
                    Délai de traitement :
                    {{ form_widget(form_delai.libelle) }}
                    {{ form_widget(form_delai.delai) }}
                    {{ form_end(form_delai) }}
                </div>
            </div>
        </div>




    </div>

{% endblock %}